# Generated by Django 4.2.23 on 2026-01-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='alerts',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
