# Generated by Django 4.2.23 on 2026-01-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_item_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('quarantine', 'Quarantine')], default='active', max_length=20),
        ),
    ]
