# Generated by Django 4.2.23 on 2026-01-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_item_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['supplier'], name='api_item_supplie_ca5bd4_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['inspected_by'], name='api_item_inspect_1185f4_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['accepted_or_rejected'], name='api_item_accepte_82cd8f_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['category'], name='api_item_categor_7a75e7_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['created_at'], name='api_item_created_a43037_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['expiry_date'], name='api_item_expiry__6a9cef_idx'),
        ),
    ]
